In [1]:
from generalist_rl.impl.environment.gymnasium import GymEnv
from generalist_rl.api.environment import Action

Importing module 'gym_37' (/home/elijah/Downloads/IsaacGym_Preview_3_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/elijah/Downloads/IsaacGym_Preview_3_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json


/home/elijah/miniconda3/envs/isaac3/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
env = GymEnv('CartPole-v0', num_envs=3)

/home/elijah/miniconda3/envs/isaac3/lib/python3.7/site-packages/gymnasium/envs/registration.py:524: DeprecationWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  f"The environment {env_name} is out of date. You should consider "


In [3]:
env_step_result = env.reset()

In [4]:
env_step_result.obs['obs']

array([[ 0.03972591, -0.03909254,  0.01072352, -0.03372756],
       [-0.00890326, -0.03958401, -0.04211979, -0.03441735],
       [ 0.03538647, -0.02906431, -0.01575351, -0.02384686]],
      dtype=float32)

In [8]:
env_step_result.done

array([False])

In [9]:
env.step(Action(x=))

MultiDiscrete([2 2 2])

In [1]:
import torch

In [13]:
a = torch.tensor([1.0,29.0,123.0])
b = torch.tensor([2.0])

In [14]:
a.shape, b.shape

(torch.Size([3]), torch.Size([1]))

In [15]:
torch.mean(a + b)

tensor(53.)

In [16]:
torch.mean(a) + b

tensor([53.])